### ISSUE TITLE
[BUG] Plugin Version 2.4.1.0 is not compatible with Dashboards 2.4.1

### ISSUE THREAD

**Issue by hashworks** [opensearch-project/dashboards-visualizations#146]
**What is the bug?**
Using plugin version 2.4.1.0:
```
Plugin "ganttChartDashboards" is only compatible with OpenSearch Dashboards version "2.4.0", but used OpenSearch Dashboards version is "2.4.1". (incompatible-version, /usr/share/opensearch-dashboards/plugins/ganttChartDashboards/opensearch_dashboards.json)
```

**How can one reproduce the bug?**
1. Build tag 2.4.1.0
2. Use in OpenSearch Dashboards 2.4.1

**What is the expected behavior?**
I expect the version 2.4.1.X to work with Dashboards 2.4.1.

**What is your host/environment?**
 - OS: Arch Linux
 - Version: 2.4.1.0

**Comment by hashworks** [comment]
@gaiksaya I see you [bumped the version](https://github.com/opensearch-project/dashboards-visualizations/commit/33271b813de98aaa2e6377013aa3e5f4699f04bf), is it *really* not compatible?

**Comment by gaiksaya** [comment]
Tagging the [maintainers](https://github.com/opensearch-project/dashboards-visualizations/blob/main/MAINTAINERS.md) of this component @joshuali925 
cc: @anirudha @rupal-bq
