### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-visualizations#21]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by AMoo-Miki** [comment]
@joshuali925, I believe #35 addresses the concerns remaining since #22. If so, is this issue resolved?

**Comment by joshuali925** [comment]
yes, forgot to close this. thanks
