### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-visualizations#33]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [ ] Passing CI on Windows
- [ ] Documentation

**Comment by dblock** [comment]
Adding Windows CI will ensure that the plugin actually works on Windows, we can't assume that it works because it's theoretically portable.

**Comment by dblock** [comment]
I don't believe integration tests are running, and integration tests are very much part of CI. Reopening. Please close when this and any other gaps between Linux/Windows CI/CD are covered.

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.

**Comment by CEHENKLE** [comment]
@anirudha Can you please address @dblock's questions?

**Comment by CEHENKLE** [comment]
@anirudha Poke!

**Comment by CEHENKLE** [comment]
@anirudha Can you address @dblock's question?

**Comment by rupal-bq** [comment]
Closing this as there are no gaps between Linux/Windows CI/CD.
