### ISSUE TITLE
[BUG] Applies filters when it should not when ignoreFilterIfFieldNotInIndex setting is on

### ISSUE THREAD

**Issue by JacobBrandt** [opensearch-project/dashboards-visualizations#43]
**Describe the bug**
This visualization does not account for the advanced setting "ignoreFilterIfFieldNotInIndex"

**To Reproduce**
Turn setting on.
Add a filter that uses a field not in the index of the saved Gannt chart.
Watch visualization apply the filter

**Expected behavior**
Visualization should not apply the filter with the setting on

**Comment by joshuali925** [comment]
thanks for submitting an issue. we are using `buildOpenSearchQuery` to process filters, i see there is a `ignoreFilterIfFieldNotInIndex` option that can be passed in. should be a quick fix

code ref: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9e4e5ff43900b3875c1653b251aa5c71efa2569e/src/plugins/data/common/opensearch_query/opensearch_query/build_opensearch_query.ts#L61
