### ISSUE TITLE
[2.0.0][BUG] build failure due to enzyme-adapter-react

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/dashboards-visualizations#63]
OpenSearch Dashboards distributions can build with GANTT plugin due to dependency mismatch:
```
enzyme-adapter-react-16
      ^1.15.5 => opensearch-dashboards
      ^1.15.2 => gantt-chart-dashboards
```

Please update this as soon as possible:
https://github.com/opensearch-project/dashboards-visualizations/blob/main/gantt-chart/package.json#L24

Thank you!

**Comment by peternied** [comment]
@vamsi-amazon this is blocking the distribution build - can you look into it?

**Comment by anirudha** [comment]
@joshuali925 @Eric / thanks
